services:
  elastic:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.20 # Elastic 8.17.4 버전의 이미지
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9200:9200 # 9200번 포트에서 Elasticsearch 실행
    environment:
      # 아래 설정은 개발/테스트 환경에서 간단하게 테스트하기 위한 옵션 (운영 환경에서는 설정하면 안 됨)
      - discovery.type=single-node # 단일 노드 (지금은 알 필요 없음)
#      - xpack.security.enabled=false # 보안 설정
#      - xpack.security.http.ssl.enabled=false # 보안 설정
      
      
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.20 # 8.17.4 버전
    ports:
      - 5601:5601 # 5601번 포트에서 kibana 실행
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200 # kibana가 통신할 Elasticsearch 주소 알려주기
      -
  mysql:
    image: mariadb:10.9
    ports:
      - 3307:3306       # 외부 충돌을 피하기 위해 내 컴퓨터에서는 3307로 접속!
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=coupang       # 처음에 자동으로 만들 데이터베이스 이름 (선택사항)